### ISSUE TITLE
Launchfile isnt working with TiM 781S

### ISSUE THREAD

**Issue by pfedom** [SICKAG/sick_scan2#10]
Hi, 
I am using a TiM781S and the launch file isnt working. 
I tried it on: Ubuntu 20.04 with foxy. 
I changed the hostname port and frame_id for the launchfile. The exact error is attached at the bottom. 

Also the ros2 run command I used before isn't working anymore: 
ros2 run sick_scan2 sick_generic_caller __hostname:=192.168.1.24 __port:=2113 __name:=sick_tim_7xxS __frame_id:=base_scan

Thanks in advance! 
If you need more information just tell me and I'll provide it. 

**Here is my whole terminal print when I try the launch file:** 
[INFO] [launch]: All log files can be found below /root/.ros/log/2020-08-13-11-42-14-786077-AGV-Research-Rudi-128      
[INFO] [launch]: Default logging verbosity is set to INFO                                                               
[WARNING] [launch_ros.actions.node]: Parameter file path is not a file: /home/sick_scan_ws/install/sick_scan2/share/sick_scan2/config/sick_tim_7xxS.yaml                                                                                       
[INFO] [sick_generic_caller-1]: process started with pid [130]                                                          
[sick_generic_caller-1] [ERROR] [1597318934.961745895] [rcl]: Failed to parse global arguments                          [sick_generic_caller-1]                                                                                                 
[sick_generic_caller-1] >>> [rcutils|error_handling.c:108] rcutils_set_error_state()                                    
[sick_generic_caller-1] This error state is being overwritten:                                                         
 [sick_generic_caller-1]                                                                                                 
[sick_generic_caller-1]   'Couldn't parse params file: '--params-file /home/sick_scan_ws/install/sick_scan2/share/sick_scan2/config/sick_tim_7xxS.yaml'. Error: Error opening YAML file, at /tmp/binarydeb/ros-foxy-rcl-yaml-param-parser-1.1.6/src/parser.c:1782, at /tmp/binarydeb/ros-foxy-rcl-1.1.6/src/rcl/arguments.c:391'                                       
 [sick_generic_caller-1]                                                                                                
 [sick_generic_caller-1] with this new error message:                                                                   
 [sick_generic_caller-1]                                                                                                 
[sick_generic_caller-1]   'context is zero-initialized, at /tmp/binarydeb/ros-foxy-rcl-1.1.6/src/rcl/context.c:51'      [sick_generic_caller-1]                                                                                                 
[sick_generic_caller-1] rcutils_reset_error() should be called after error handling to avoid this.                      
[sick_generic_caller-1] <<<                                                                                             
[sick_generic_caller-1] [ERROR] [1597318934.961879152] [rclcpp]: failed to finalize context: context is zero-initialized, at /tmp/binarydeb/ros-foxy-rcl-1.1.6/src/rcl/context.c:51                                                             
[sick_generic_caller-1] terminate called after throwing an instance of 'rclcpp::exceptions::RCLInvalidROSArgsError'     [sick_generic_caller-1]   what():  failed to initialize rcl: error not set                                              
[ERROR] [sick_generic_caller-1]: process has died [pid 130, exit code -6, cmd '/home/sick_scan_ws/install/sick_scan2/lib/sick_scan2/sick_generic_caller --ros-args -r __node:=sick_scan2_tim_7xxS --params-file /home/sick_scan_ws/install/sick_scan2/share/sick_scan2/config/sick_tim_7xxS.yaml'].

**Error when trying ros2 run...:** 
[WARN] [1597319344.805574338] [rcl]: Found remap rule '__name:=sick_tim_7xxS'. This syntax is deprecated. Use '--ros-args --remap __name:=sick_tim_7xxS' instead.                                                                               
[INFO] [1597319344.842864412] [sick_tim_7xxS]: sick_generic_caller V. 002.000.000                                       
[INFO] [1597319344.843244763] [sick_tim_7xxS]: Program arguments: /home/sick_scan_ws/install/sick_scan2/lib/sick_scan2/sick_generic_caller                                                                                                      [INFO] [1597319344.843388440] [sick_tim_7xxS]: Program arguments: __hostname:=192.168.1.24                              
[INFO] [1597319344.843421084] [sick_tim_7xxS]: Program arguments: __port:=2113                                          
[INFO] [1597319344.843473150] [sick_tim_7xxS]: Program arguments: __name:=sick_tim_7xxS                                
 [INFO] [1597319344.843558944] [sick_tim_7xxS]: Program arguments: __frame_id:=base_scan                                 
Scanner not supported.                                                                                                  
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*'

**Comment by michael1309** [comment]
The start logic and the parsing of the parameters was changed during the ROS2 development. We recommend that you look at the last launch examples and change the call accordingly.
