### ISSUE TITLE
ROS-TIME Information/time stamp-TIM571/TIM581

### ISSUE THREAD

**Issue by jerryguo111** [SICKAG/sick_scan2#11]
Dear supportter:

We have got the time information or time stamp of TIM571/TIM581 from the TCP/IP Client port,but how to find from the ROS?or some command to find it.

**Comment by michael1309** [comment]
The timestamp is included in the ros message header (given in [sec] and [nanosec]). By using the Software-PLL mechanism you can match the internal generation ticks to the system time (see https://github.com/SICKAG/sick_scan/blob/master/doc/software_pll.md ).

**Comment by michael1309** [comment]
closed due to inactivity
