### ISSUE TITLE
is it possible to run the code in ros2 dashing?

### ISSUE THREAD

**Issue by Phymin** [SICKAG/sick_scan2#12]
Hi,

Currently I have compliled this repository in ros2 dashing, I use sick LMS151, and when I run the launch file "sick_lms_1xx.launch.py", I just got the following output:
```
[INFO] [launch]: All log files can be found below /home/phymin/.ros/log/2020-10-13-16-59-19-014711-phymin-XPS-15-9550-13027
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [sick_generic_caller-1]: process started with pid [13037]
```
and nothing more information.

So I am wondering if the code is compatible with ros2 dashing, or should I change something? Hope someone could give me some clue, Thanks.

**Comment by michael1309** [comment]
The current version of the ROS2 driver is optimized for Foxy. We have noticed that earlier versions partly do not adopt the naming convention in the YAML files correctly by ROS2. We will check this and adapt it if appropriate.

**Comment by michael1309** [comment]
closed due to inactivity and dashing EOL in May 2021
