### ISSUE TITLE
Is it possible to set all parameters via ros, which can be set in sopas?

### ISSUE THREAD

**Issue by Kaju-Bubanja** [SICKAG/sick_scan2#17]
There are some parameters I can not find how to set them via ros e.g. the echo filter or the particle filter, the mean filter, the fog filter and the multiecho handling. There are also others. Does ros only expose a subset of the options of the sensor? And if I change them in sopas will the change be reflected when running the sensor using the ros drivers or will the drivers overwrite these parameters with some defaults? I checked the sick_generic_caller.cpp file and didn't find all parameters, so I assume the driver won't overwrite the set config on the sensor?

**Comment by michael1309** [comment]
Hello @Kaju-Bubanja ,

You are right in your assumption.
Yes the driver uses only a subset of the Lidar configurations, especially settings like particle or fog filters are not modified by the driver. If these parameters are set in SOPAS ET and then stored in the EEPROM, this driver does not overwrite the parameters and the lidar works with these settings.

best regards
