### ISSUE TITLE
adjustments user manual

### ISSUE THREAD

**Issue by Edwin123456789** [SICKAG/sick_scan2#19]
Hi,

The sensor I use is the TIM571 and I was following the manual to get the device working. I came across some details, for the package didn't work straight out of the box for me.

'Default is "laser"' should be "cloud" according to me. The sensor TIM571 doesn't show anything in RVIZ with 'ros2 run tf2_ros static_transform_publisher 0 0 0 0 0 0 world laser'. Should be 'ros2 run tf2_ros static_transform_publisher 0 0 0 0 0 0 world cloud' I think.

Another thing: the "For a quick build, install and run test" comments work indeed. Very handy such ./makeall.bash and ./makeall.bash files. But for the demo above I had to add 
-p "sw_pll_only_publisch:=False"
at 'ros2 run sick_scan2 sick_generic_caller --ros-args --params-file src/sick_scan2/config/sick_tim_5xx.yaml -p "hostname:=127.0.0.1" -p "port:=2112"'

**Comment by michael1309** [comment]
Hi Edwin,

Thanks for you friendly user feedback. We would like to integrate your hints into the description in the next couple of days.

Best regards,
Michael

**Comment by michael1309** [comment]
We did it. Thanks again.
