### ISSUE TITLE
Support USB-Connection

### ISSUE THREAD

**Issue by Darkproduct** [SICKAG/sick_scan2#22]
Hi, we have 2 Sick Tim 571 and we would like to connect them via USB to the main computer. The simple reason is, that we have multiple free USB slots, but only one Network connection slot and we don't want to add an Network HUB as well.

The [sick-tim package](https://github.com/uos/sick_tim) supports USB connection, but this package is not available in ROS2. Since the source code of this package is very similar, it shouldn't be too hard to port this functionality. Are the currently any plans to do so and would you be interested in a pull-request if we decide to port it by our self?

Currently, we run the sick-tim driver on ROS Noetic and use the ROS1 bridge only for the scan topics.

**Comment by heizmreSICKAG** [comment]
Hi Darkproduct, unfortunately USB is not a supported data interface. An USB connection offers parallel access to diagnostics and parameterization only. For visualization purpose there is also scandata passing this interface but of minor performance and intended for internal use with SOPAS ET only. The command interface for USB is not documented and partly differs from Ethernet, especially for scandata. Therefore, USB is of secondary importance for the ROS framework and we have no plans to support and maintain this interface by our packages. Please give us a hint if you decide to implement this feature anyway. 
Best regards Reinhard

**Comment by Darkproduct** [comment]
Currently, we are planning to set it up with the old `sick-tim` driver for `ROS Noetic` and the `ROS2 Bridge`. We have an `Raspberry Pi` as main computer and there is only one LAN Port available.

Can you elaborate what you mean with "minor performance"? Do we risk loosing messages by using USB?

**Comment by rostest** [comment]
Closed due to out of scope and answered by SICK management.

**Comment by Darkproduct** [comment]
@heizmreSICKAG I'm still wondering if I could get an answer regarding:

> Can you elaborate what you mean with "minor performance"? Do we risk loosing messages by using USB?

**Comment by heizmreSICKAG** [comment]
Yes, there is a risk loosing messages as the USB interface is not intended to run at scanrate. Sorry that I can't give you more details on this but USB is not specified for scandata access.
