### ISSUE TITLE
Add an option to filter scan by intensity for ROS2 

### ISSUE THREAD

**Issue by INGU2018** [SICKAG/sick_scan2#23]
I would like to know you have a plan to apply same issue as #131 of sick scan github(https://github.com/SICKAG/sick_scan/issues/131). 
Also, It seems that sick_scan2 is far behind sick_scan. I want to update sick_scan by sick_scan2.

**Comment by michael1309** [comment]
We are working on a migration of sick_scan and sick_scan2 to a common repository. Release is planned at latest end of Oct. 21. In this migrated repo. we will also support the mentioned filter mechanism for ROS 1 and ROS 2.

**Comment by INGU2018** [comment]
I have one more question. Will the features of diagnostic updater in sick scan(ROS 1) be applied to the common repository as well?

**Comment by rostest** [comment]
In the Linux-version, the diagnostic updater will be supported on both ROS-1 and ROS-2. On ROS-2 under Windows the diagnostic updater will not be supported in the first place (diagnostic_updater on Windows requires at least foxy patch 4).
