### ISSUE TITLE
Setting IP Address of node at launch 

### ISSUE THREAD

**Issue by RalphCodesTheInternet** [SICKAG/sick_scan2#40]
How can I set the IP address of my Tim5 when I launch the ROS node?

ros2 launch sick_scan2 sick_tim_5xx.launch.py hostname:="192.168.1.1"   does not seem to work.

The config yml file can be edited, but this limits the ability to use more than one scanner. How can I launch multiple nodes with different IP addresses?

**Comment by rostest** [comment]
The IP address can be set by 
```
ros2 run sick_scan2 sick_generic_caller --ros-args --params-file src/sick_scan2/config/sick_tim_5xx.yaml -p "hostname:=192.168.1.1"
```
sick_scan2 publishes the point cloud on topic "cloud". To run multiple nodes concurrently, each node must use a different ros topic. We therefor recommend switching to the sick_scan_xd driver on https://github.com/SICKAG/sick_scan_xd. See https://github.com/SICKAG/sick_scan_xd#start-multiple-nodes and https://github.com/SICKAG/sick_scan_xd/blob/master/doc/faq.md#how-to-run-multiple-sensors-concurrently on how to run multiple nodes. The sick_scan_xd driver contains the most recent releases to support TiM and other lidars.
