### ISSUE TITLE
No data received even after successful scanner initialization

### ISSUE THREAD

**Issue by mayankpathak10** [SICKAG/sick_scan2#41]
Connection to the Lidar was successful with terminal last terminal output being `Starting scan data ....`. However, no data is published on any ros2 topic, as shown in the image below.

![Screenshot from 2022-05-11 15-16-03](https://user-images.githubusercontent.com/33289342/167931880-b9bd4a59-7e0d-410c-ad97-ef0622307ed3.png)

**Comment by rostest** [comment]
Thanks for reporting. Please use https://github.com/SICKAG/sick_scan_xd for the most recent driver release.

The screenshot showing the messages looks okay, i.e. the lidar should send scandata. You can check the topic output for ros2 by using the following commands:
`ros2 topic echo /cloud`
If you have further problems, please send us a detailed description of the lidar type you are using and the overall starting log screenshot after launching the ros node.

**Comment by mayankpathak10** [comment]
Thanks for responding. I have tried echoing to `/cloud`, `/scan`, and `/imu`. No data is published on these topics.
Anyways, I have now tried running driver from the 'sick_scan_xd' repo, still not getting the data. Also, note that I am not getting any data on SOPAS as well. I will open a detailed issue on the 'sick_scan_xd' repo.
