### ISSUE TITLE
C++17 compatibility

### ISSUE THREAD

**Issue by tommy-erko** [SICKAG/sick_scan2#47]
Not a troublemaker for now, but it might by worthy to keep in mind, there are several occurences in **sick_scan2/driver/src/binPrintf.cpp** (compiler warning, gcc version 11.2.0):
`warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]`

**Comment by rostest** [comment]
Thanks for your friendly reminder. We recommend using https://github.com/SICKAG/sick_scan_xd for the further development. sick_scan_xd provides the most recent driver releases for all supported lidars.
