### ISSUE TITLE
Parameter to configure sensor frame in scan message

### ISSUE THREAD

**Issue by IanTheEngineer** [SICKAG/sick_scan2#6]
The frame `laser` is quite common onboard a robot with multiple lidars. It would be very appreciated if the code supported grabbing a scan frame parameter, so that the Transforms could be reprojected into a specific lidar's frame ( allowing the use of multiple TIM's :). This could be done in a very similar manner to the `min_angle` and `max_angle` parameters:
https://github.com/SICKAG/sick_scan2/blob/master/driver/src/sick_scan_common.cpp#L246-L251
```
	double min_angle = node->declare_parameter(PARAM_MIN_ANG, -2.35619449);
	double max_angle = node->declare_parameter(PARAM_MAX_ANG, +2.35619449);

	cfg.min_ang = min_angle;
	cfg.max_ang = max_angle;
	cfg.frame_id = "laser";    // <---- requesting to make this configurable
```
Thank you for your effort on this repo!

**Comment by michael1309** [comment]
We will integrate it until end of this week.

**Comment by michael1309** [comment]
@IanTheEngineer

Since version 0.1.5 this is implemented.
Via the program argument __frame_id the frame of the laserscan messages can be changed. 
__frame_id:=your_frame_id

We hope that this solves your Problems.

**Comment by IanTheEngineer** [comment]
Excellent! Thank you @michael1309
