### ISSUE TITLE
bloom-release into ROS Eloquent

### ISSUE THREAD

**Issue by IanTheEngineer** [SICKAG/sick_scan2#7]
We've found this repository quite helpful, but have migrated to ROS Eloquent. Could you `bloom-release` this package into `rosdistro eloquent`? Thanks!

**Comment by michael1309** [comment]
Thanks for your interest. We will discuss this issue with the management and give you a feedback until end of this month.

**Comment by olmerg** [comment]
some news in the inclusion in the ros package distro

**Comment by michael1309** [comment]
Migrated to ROS foxy by using bloom release.
